"""Generic Pydantic models for GeoJSON output (RFC 7946).

These are the generic building blocks. For typed endpoint responses, define
a concrete FeatureCollection by specifying the properties model, e.g.:

    class LeadsFeatureCollection(FeatureCollection[LeadProperties]):
        pass

Swagger/OpenAPI will render the concrete model name, not the generic base,
giving the operator a readable schema for every spatial endpoint.

GIS contract:
    - geometry.coordinates are ALWAYS in WGS84 (EPSG:4326), longitude first.
    - Projection to EPSG:4326 happens in the SQL query via ST_Transform(geom, 4326),
      never in Python.
    - The `geometry` field accepts the raw dict produced by ST_AsGeoJSON(), which is
      already a valid GeoJSON Geometry object.
"""

from __future__ import annotations

from typing import Any, Generic, Literal, Optional, TypeVar

from pydantic import BaseModel, ConfigDict, Field

T = TypeVar("T", bound=BaseModel)

# ---------------------------------------------------------------------------
# Geometry types
# ---------------------------------------------------------------------------

GeoJSONGeometryType = Literal[
    "Point",
    "MultiPoint",
    "LineString",
    "MultiLineString",
    "Polygon",
    "MultiPolygon",
    "GeometryCollection",
]


class GeoJSONGeometry(BaseModel):
    """A GeoJSON Geometry object.

    coordinates are WGS84 [lon, lat] (or [lon, lat, alt]).
    Generated by PostGIS via ST_AsGeoJSON(ST_Transform(geom, 4326))::json.
    """

    model_config = ConfigDict(extra="allow")  # allow 'geometries' for GeometryCollection

    type: GeoJSONGeometryType
    coordinates: Optional[Any] = Field(
        default=None,
        description="Coordinate array — structure varies by geometry type",
    )


# ---------------------------------------------------------------------------
# Generic Feature / FeatureCollection
# ---------------------------------------------------------------------------

class Feature(BaseModel, Generic[T]):
    """RFC 7946 GeoJSON Feature with a typed properties object."""

    type: Literal["Feature"] = Field(default="Feature", frozen=True)
    geometry: Optional[GeoJSONGeometry] = Field(
        description="Geometry in WGS84 (EPSG:4326). NULL for feature without location."
    )
    properties: T = Field(description="Feature-specific metadata")


class FeatureCollection(BaseModel, Generic[T]):
    """RFC 7946 GeoJSON FeatureCollection.

    Extended with a top-level `count` field (ignored by Mapbox / MapLibre, but
    useful for dashboard pagination without an extra HTTP round-trip).
    """

    type: Literal["FeatureCollection"] = Field(default="FeatureCollection", frozen=True)
    features: list[Feature[T]] = Field(
        description="List of GeoJSON Feature objects"
    )
    count: int = Field(
        ge=0,
        description="Number of features in this response (capped by `limit`)",
    )
